In [18]:
import numpy as np
import cv2
import glob
import matplotlib.pyplot as plt

## CALIBRATION

The process of calibrating an image consists of mainly 3 steps: 1) find chessboard-corners in a dataset of images containing a chessboard. 2) Use the corner points to compute a camera matrix. 3) Use the camera matrix to undistort images.

In [91]:
def calibration():
    # termination criteria
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 50, 0.001)
    """
    Implement the number of vertical and horizontal corners
    nb_vertical = ...
    nb_horizontal = ...
    """
    nb_vertical = 5
    nb_horizontal = 7
    # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
    objp = np.zeros((5*7,3), np.float32)
    objp2 = np.zeros((5*7,3), np.float32)
    objp[:,:2] = np.mgrid[0:5,0:7].T.reshape(-1,2)
    objp2[:,:2] = np.mgrid[0:5,0:7].T.reshape(-1,2)

    # Arrays to store object points and image points from all the images.
    objpoints = [] # 3d point in real world space
    imgpoints_left = [] # 2d points in image plane.
    imgpoints_right = [] # 2d points in image plane.

    images_left = sorted(glob.glob('raw_videos/calib/image_02/data/*.png'))
    images_right = sorted(glob.glob('raw_videos/calib/image_03/data/*.png'))
    assert images_left
    assert images_right
    
    for i in range(0,len(images_left)):
        img_left= cv2.imread(images_left[i])
        img_right = cv2.imread(images_right[i])
        
        gray_left = cv2.cvtColor(img_left, cv2.COLOR_BGR2GRAY)
        gray_right = cv2.cvtColor(img_right, cv2.COLOR_BGR2GRAY)
        
    # Detecting first chessboard
        # Cropping an image
        gray_left_cropped = gray_left[250:450, 800:1000]
        gray_right_cropped = gray_right[250:450, 720:920]
        
        ret_left, corners_left = cv2.findChessboardCorners(gray_left_cropped, (nb_vertical,nb_horizontal), None)
        ret_right, corners_right = cv2.findChessboardCorners(gray_right_cropped, (nb_vertical,nb_horizontal), None)
        
            
        # If found, add object points, image points (after refining them)
        if ret_left == True and ret_right == True:
            objpoints.append(objp)
            
            corners2_left = cv2.cornerSubPix(gray_left_cropped, corners_left, (7, 7), (-1, -1), criteria)
            corners2_right = cv2.cornerSubPix(gray_right_cropped, corners_right, (7, 7), (-1, -1), criteria)
            
            for i in range(0,len(corners2_left)):
                corners2_left[i][0][0] = corners2_left[i][0][0] + 800
                corners2_left[i][0][1] = corners2_left[i][0][1] + 250
                corners2_right[i][0][0] = corners2_right[i][0][0] + 720
                corners2_right[i][0][1] = corners2_right[i][0][1] + 250
               
            imgpoints_left.append(corners2_left)
            imgpoints_right.append(corners2_right)

            # Draw the corners
            img_left = cv2.drawChessboardCorners(img_left, (nb_vertical,nb_horizontal), corners2_left, ret_left)
            img_right = cv2.drawChessboardCorners(img_right, (nb_vertical,nb_horizontal), corners2_right, ret_right)
    
        # Detecting the second chessboard   
        gray_left_cropped = gray_left[50:250, 800:1000]
        gray_right_cropped = gray_right[50:250, 700:900]
        
        ret_left, corners_left = cv2.findChessboardCorners(gray_left_cropped, (nb_vertical,nb_horizontal), None)
        ret_right, corners_right = cv2.findChessboardCorners(gray_right_cropped, (nb_vertical,nb_horizontal), None)
        
         # If found, add object points, image points (after refining them)
        if ret_left == True and ret_right == True:
            objpoints.append(objp)
            
            corners2_left = cv2.cornerSubPix(gray_left_cropped, corners_left, (7, 7), (-1, -1), criteria)
            corners2_right = cv2.cornerSubPix(gray_right_cropped, corners_right, (7, 7), (-1, -1), criteria)
            
            for i in range(0,len(corners2_left)):
                corners2_left[i][0][0] = corners2_left[i][0][0] + 800
                corners2_left[i][0][1] = corners2_left[i][0][1] + 50
                corners2_right[i][0][0] = corners2_right[i][0][0] + 700
                corners2_right[i][0][1] = corners2_right[i][0][1] + 50
               
            imgpoints_left.append(corners2_left)
            imgpoints_right.append(corners2_right)

            # Draw the corners
            img_left = cv2.drawChessboardCorners(img_left, (nb_vertical,nb_horizontal), corners2_left, ret_left)
            img_right = cv2.drawChessboardCorners(img_right, (nb_vertical,nb_horizontal), corners2_right, ret_right)
        
        # Detecting the third chessboard   
        gray_left_cropped = gray_left[200:400, 1000:1250]
        gray_right_cropped = gray_right[200:400, 900:1150]
       # cv2.imshow('img',gray_right_cropped)
        #cv2.waitKey(1000)
        ret_left, corners_left = cv2.findChessboardCorners(gray_left_cropped, (nb_vertical,nb_horizontal), None)
        ret_right, corners_right = cv2.findChessboardCorners(gray_right_cropped, (nb_vertical,nb_horizontal), None)
        
         # If found, add object points, image points (after refining them)
        if ret_left == True and ret_right == True:
            objpoints.append(objp)
            
            corners2_left = cv2.cornerSubPix(gray_left_cropped, corners_left, (7, 7), (-1, -1), criteria)
            corners2_right = cv2.cornerSubPix(gray_right_cropped, corners_right, (7, 7), (-1, -1), criteria)
            
            for i in range(0,len(corners2_left)):
                corners2_left[i][0][0] = corners2_left[i][0][0] + 1050
                corners2_left[i][0][1] = corners2_left[i][0][1] + 200
                corners2_right[i][0][0] = corners2_right[i][0][0] + 950
                corners2_right[i][0][1] = corners2_right[i][0][1] + 200
               
            imgpoints_left.append(corners2_left)
            imgpoints_right.append(corners2_right)

            # Draw the corners
            img_left = cv2.drawChessboardCorners(img_left, (nb_vertical,nb_horizontal), corners2_left, ret_left)
            img_right = cv2.drawChessboardCorners(img_right, (nb_vertical,nb_horizontal), corners2_right, ret_right)
            
            
        # Detecting the forth chessboard      
        gray_left_cropped = gray_left[:, 0:400]
        gray_right_cropped = gray_right[:, 0:400]
        
        ret_left, corners_left = cv2.findChessboardCorners(gray_left_cropped, (11,7), None)
        ret_right, corners_right = cv2.findChessboardCorners(gray_right_cropped, (11,7), None)
        
         # If found, add object points, image points (after refining them)
        if ret_left == True and ret_right == True:
            objpoints.append(objp)
            corners2_left = cv2.cornerSubPix(gray_left_cropped, corners_left, (7, 7), (-1, -1), criteria)
            corners2_right = cv2.cornerSubPix(gray_right_cropped, corners_right, (7, 7), (-1, -1), criteria)
            
            imgpoints_left.append(corners2_left[0:35])
            imgpoints_right.append(corners2_right[0:35])
            

            img_left = cv2.drawChessboardCorners(img_left, (11,7), corners2_left, ret_left)
            img_right = cv2.drawChessboardCorners(img_right, (11,7), corners2_right[0:35], ret_right)
            
            plot_image = np.concatenate((img_left, img_right), axis=1)
            #plot_image = np.vstack((img_left, img_right))
            cv2.imshow('img',plot_image)
            cv2.waitKey(1000)
        
    
    cv2.destroyAllWindows()
    # Frame dimensions. Frames should be the same size.
    w = img_left.shape[1]
    h = img_left.shape[0]
    print(w, h)
    
    # Get the camera matrix
    ret, K_left, dist_left, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints_left, gray_left.shape[::-1], None, None) 
    ret, K_right, dist_right, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints_right, gray_right.shape[::-1], None, None)
    
    # Calibrate the stereo camera setup
    stereocalibration_flags = cv2.CALIB_FIX_INTRINSIC
    criteria_stereo= (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 50, 0.001)
    
    ret, CM_left, CM_dist_left, CM_right, CM_dist_right, R, T, E, F = cv2.stereoCalibrate(objpoints, imgpoints_left, imgpoints_right, K_left, dist_left,
                                                                                    K_right, dist_right, (w, h), criteria = criteria_stereo, flags = stereocalibration_flags)

    return CM_left, CM_right, CM_dist_left, CM_dist_right, R, T, F


In [92]:
(K_left, K_right, dist_left, dist_right, R, T, F) = calibration()

print("K_left: ",  K_left)
print ("Dist_left: ", dist_left)
print("K_right: ",  K_right)
print ("Dist_right", dist_right)
print("R:", R)
print("T: ", T)
print("F: ", F)

1392 512
K_left:  [[420.79075487   0.         882.28498888]
 [  0.         458.82147516 266.02126249]
 [  0.           0.           1.        ]]
Dist_left:  [[ 0.48369225  0.20845372 -0.13256534  0.03033536 -0.23010908]]
K_right:  [[568.102483     0.         698.4106223 ]
 [  0.         643.03225644 261.24408749]
 [  0.           0.           1.        ]]
Dist_right [[ 0.02230363 -0.00626007 -0.04006836 -0.00254069 -0.08591406]]
R: [[ 0.38829627  0.70562936 -0.59271681]
 [ 0.23043464  0.54840441  0.8038361 ]
 [ 0.89225887 -0.44870904  0.05034194]]
T:  [[ 31.46659704]
 [-30.93375973]
 [ 86.89060017]]
F:  [[ 2.80673237e-06  1.82534495e-06 -1.19114693e-03]
 [-2.94859952e-07 -3.60205982e-06  2.38147321e-03]
 [-2.52815909e-03 -1.53395741e-03  1.00000000e+00]]


## UNDISTORSION

Using the extracted corners we can obtain a camera matrix that contains the information needed to undistort images

In [59]:
def undistort(K_left, K_right, dist_left, dist_right):
    images_left = sorted(glob.glob('raw_videos/calib/image_02/data/*.png'))
    images_right = sorted(glob.glob('raw_videos/calib/image_03/data/*.png'))
    assert images_left
    assert images_right
    
    path_out_left = 'raw_videos/calib/image_02/undistorted/left/left-'
    path_out_right = 'raw_videos/calib/image_02/undistorted/right/right-'
    print(path_out_left)
    # Get optimal intrinsic matrix based on parameter alpha (used for rectification?)
    '''if alpha>0, the undistorted result is likely to have some black pixels corresponding to "virtual" pixels outside of the captured distorted image'''
    (h,w) = cv2.imread(images_left[0]).shape[0:2]
    K_new_left, roi_left = cv2.getOptimalNewCameraMatrix(K_left, dist_left,(w,h), alpha=0)
    K_new_right, roi_right = cv2.getOptimalNewCameraMatrix(K_right, dist_right,(w,h), alpha=0)
    

    for i in range(len(images_left)):
        # Undistort
        img_left= cv2.imread(images_left[i])
        img_right = cv2.imread(images_right[i])
        
        dst_left = cv2.undistort(img_left, K_left, dist_left, None, K_new_left)
        dst_right = cv2.undistort(img_right, K_right, dist_right, None, K_new_right)

        # Crop the image
        x, y, w, h = roi_left
        dst_left = dst_left[y:y+h, x:x+w]
        
        x, y, w, h = roi_right
        dst_right = dst_right[y:y+h, x:x+w]

        # Save image
        cv2.imwrite(path_out_left+str(i)+'.png', img_left)
        cv2.imwrite(path_out_right+str(i)+'.png', dst_right)

## RECTIFICATION


In [ ]:
def draw_lines(img1, img2, lines, pts1, pts2):
    ''' img1 - image on which we draw the epilines for the points in img2
        lines - corresponding epilines '''
    (r, c,_) = img1.shape
    # r,c = img1.shape
    # img1 = cv2.cvtColor(img1,cv2.COLOR_GRAY2BGR)
    # img2 = cv2.cvtColor(img2,cv2.COLOR_GRAY2BGR)
    for r, pt1, pt2 in zip(lines, pts1, pts2):
        color = tuple(np.random.randint(0, 255, 3).tolist())
        x0, y0 = map(int, [0, -r[2]/r[1]])
        x1, y1 = map(int, [c, -(r[2]+r[0]*c)/r[1]])
        img1 = cv2.line(img1, (x0, y0), (x1, y1), color, 2)
        img1 = cv2.circle(img1, tuple(pt1), 5, color, -1)
        img2 = cv2.circle(img2, tuple(pt2), 5, color, -1)
    return img1, img2

def draw_epipolar_lines(img_left, img_right):
    '''Draws epipolar lines to the image'''
    
    # # Change to RGB
    # gray_left = cv2.cvtColor(img_left, cv2.COLOR_BGR2GRAY)
    # gray_right = cv2.cvtColor(img_right, cv2.COLOR_BGR2GRAY)

    # Find the keypoints and descriptors with SIFT
    sift = cv2.SIFT_create()
    kp_left, des_left = sift.detectAndCompute(img_left, None)
    kp_right, des_right = sift.detectAndCompute(img_right, None)

    # Match points
    matches = cv2.BFMatcher().match(des_left, des_right)
    matches = sorted(matches, key=lambda x: x.distance)
    nb_matches = 200  # Using 200 best matches
    good = []
    pts1 = []
    pts2 = []
    for m in matches[:nb_matches]:
        good.append(m)
        pts1.append(kp_left[m.queryIdx].pt)
        pts2.append(kp_right[m.trainIdx].pt)
    pts1 = np.int32(pts1)
    pts2 = np.int32(pts2)

    # Get fundamental matrix
    F, inliers = cv2.findFundamentalMat(pts1, pts2, method=cv2.FM_RANSAC)

    # Remove outliers
    pts1 = pts1[inliers.ravel() == 1]
    pts2 = pts2[inliers.ravel() == 1]

    # Draw lines
    lines1 = cv2.computeCorrespondEpilines(pts2.reshape(-1, 1, 2), 2, F)
    lines1 = lines1.reshape(-1, 3)
    epilines_left, keypoints_left = draw_lines(img_left, img_right, lines1, pts1, pts2)
    lines2 = cv2.computeCorrespondEpilines(pts1.reshape(-1, 1, 2), 1, F)
    lines2 = lines2.reshape(-1, 3)
    epilines_right, keypoints_right = draw_lines(img_right, img_left, lines2, pts2, pts1)

    fig, axs = plt.subplots(1, 2, constrained_layout=True, figsize=(10, 10))
    axs[0].imshow(epilines_left)
    axs[0].set_title('left epipolar lines')
    axs[1].imshow(epilines_right)
    axs[1].set_title('right epipolar lines')
    plt.show()

In [37]:
def rectification(CM_left, CM_dist_left, CM_right, CM_dist_right, R, T):
     
     images_left = sorted(glob.glob('raw_videos/calib/image_02/data/*.png'))
     assert images_left
     (h,w) = cv2.imread(images_left[0]).shape[0:2]
     
     R_left, R_right, P_left, P_right, Q, roi_left, roi_right= cv2.stereoRectify(CM_left, CM_dist_left, CM_right, CM_dist_right, (w,h), 
                                                    R, T, alpha=-1.0)
     map1_x, map1_y = cv2.initUndistortRectifyMap(K_left, dist_left, R_left, P_left, (w, h), cv2.CV_32FC1)
     map2_x, map2_y = cv2.initUndistortRectifyMap(K_right, dist_right, R_right, P_right, (w, h), cv2.CV_32FC1)
    
     return map1_x, map1_y, map2_x, map2_y

In [ ]:
def remap(img_left, img_right, K_left, dist_left, K_right, dist_right, R, T, leftMapX, leftMapY,rightMapX, rightMapY, debug=False):
    '''Rectify the image'''

    left_rectified = np.zeros(img_left.shape[:2], np.uint8)
    right_rectified = np.zeros(img_right.shape[:2], np.uint8)
    left_rectified = cv2.remap(img_left, leftMapX, leftMapY, cv2.INTER_LINEAR, left_rectified, cv2.BORDER_CONSTANT)
    right_rectified = cv2.remap(img_right, rightMapX, rightMapY, cv2.INTER_LINEAR, right_rectified, cv2.BORDER_CONSTANT)

    if debug:
        draw_epipolar_lines(left_rectified,right_rectified)

    return left_rectified, right_rectified

In [38]:

def rectify_uncalibrated(img_left, img_right, debug=False):  
    ''' We use the fundamental matrix from calibration.'''
    
    # Find the keypoints and descriptors with SIFT
    sift = cv2.SIFT_create()
    kp_left, des_left = sift.detectAndCompute(img_left, None)
    kp_right, des_right = sift.detectAndCompute(img_right, None)
    [F, mask] = cv2.findFundamentalMat(kp_left, kp_right, 'Method','Ransac');
    # Match points
    matches = cv2.BFMatcher().match(des_left, des_right)
    matches = sorted(matches, key=lambda x: x.distance)
    nb_matches = 200  # Using 200 best matches
    good = []
    pts1 = []
    pts2 = []
    for m in matches[:nb_matches]:
        good.append(m)
        pts1.append(kp_left[m.queryIdx].pt)
        pts2.append(kp_right[m.trainIdx].pt)
    pts1 = np.int32(pts1)
    pts2 = np.int32(pts2)
    
    # Rectify images
    (h,w,_) = img_left.shape
    _, H1, H2 = cv2.stereoRectifyUncalibrated(np.float32(pts1), np.float32(pts2), F, (w,h))
    left_rectified = cv2.warpPerspective(img_left, H1, (w,h))
    right_rectified = cv2.warpPerspective(img_right, H2, (w,h))

    if debug:
        draw_epipolar_lines(left_rectified,right_rectified)

    return left_rectified,right_rectified

The last step is to check the results on an image:

In [61]:
calibrated = True
if calibrated:
    images_left = sorted(glob.glob('raw_videos/calib/image_02/data/*.png'))
    images_right = sorted(glob.glob('raw_videos/calib/image_03/data/*.png'))
    assert images_left
    assert images_right
else:
    undistort(K_left, K_right, dist_left, dist_right)
    images_left = sorted(glob.glob('raw_videos/calib/image_02/undistorted/left/*.png'))
    images_right = sorted(glob.glob('raw_videos/calib/image_02/undistorted/right/*.png'))
    assert images_left
    assert images_right

for i in range(0,len(images_left)):
    img_left= cv2.imread(images_left[i])
    img_right = cv2.imread(images_right[i])

    if calibrated:
        map1_x, map1_y, map2_x, map2_y = rectification(K_left, dist_left, K_right, dist_right, R, T)
        left_rectified,right_rectified = remap(img_left, img_right, K_left, dist_left, K_right, dist_right, R, T, map1_x, map1_y,map2_x, map2_y, debug=True)
    else:
        left_rectified,right_rectified = rectify_uncalibrated(img_left, img_right, debug=False)

    cv2.imshow('img',left_rectified)
    cv2.waitKey(500)
cv2.destroyAllWindows()